<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class Question extends Model
{

    protected $fillable = [
        'title',
        'lesson_id',
        'slug',
        'audio',
        'question_details',
        'status',
        'created_by',
        'updated_by',
    ];


    public function getRouteKeyName()
    {
        return 'slug';
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($question){
            $question->slug = Str::slug($question->title);
            $question->created_by = Auth::id();
        });
        static::updating(function ($question){
            $question->slug = Str::slug($question->title);
            $question->updated_by = Auth::id();
        });

    }


    public function createdUser()
    {
        return $this->belongsTo(User::class, 'created_by');
    }


    public function updatedUser()
    {
        return $this->belongsTo(User::class, 'updated_by');
    }

}
